spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/microservice_db?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: citydataapiservice
server:
  port: 8090
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka